import { Villa, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Units', icon: 'LayoutGrid' },
  { id: 'glamping', name: 'Glamping', icon: 'Tent' },
  { id: 'cabin', name: 'Cabins', icon: 'Home' },
  { id: 'family', name: 'Family Size', icon: 'Users' },
  { id: 'couple', name: 'Couple', icon: 'Heart' },
];

export const VILLAS: Villa[] = [
  {
    id: '1',
    name: 'Pine Forest Glamping',
    location: 'Area Hutan, Gondosuli',
    coordinates: { lat: -7.6667, lng: 111.1333 },
    price: 675000,
    rating: 4.8,
    reviews: 124,
    description: 'Immerse yourself in the cool Tawangmangu air. Our luxury canvas tents offer a direct connection to the pine forest while maintaining hotel-quality comfort. Perfect for couples seeking a romantic nature escape.',
    images: [
      'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?q=80&w=800&auto=format&fit=crop',
    ],
    category: 'glamping',
    facilities: [
      { name: 'Wifi', icon: 'Wifi' },
      { name: 'Breakfast', icon: 'Coffee' },
      { name: 'Bonfire', icon: 'Flame' },
    ],
    isPopular: true,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    id: '2',
    name: 'The Lawu Cabin',
    location: 'Gondosuli, Tawangmangu',
    coordinates: { lat: -7.6650, lng: 111.1350 },
    price: 1275000,
    rating: 4.9,
    reviews: 89,
    description: 'A modern wooden cabin with floor-to-ceiling windows facing Mount Lawu. Features a private terrace for morning coffee and a warm, minimalist interior designed for deep relaxation.',
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?q=80&w=800&auto=format&fit=crop',
    ],
    category: 'cabin',
    facilities: [
      { name: 'Wifi', icon: 'Wifi' },
      { name: 'Parking', icon: 'Car' },
      { name: 'Heater', icon: 'Thermometer' },
    ],
    isNew: true,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    id: '3',
    name: 'Omah Turu Joglo',
    location: 'Area Hutan, Gondosuli, Kec. Tawangmangu, Kabupaten Karanganyar, Jawa Tengah 57792',
    coordinates: { lat: -7.6680, lng: 111.1320 },
    price: 2700000,
    rating: 5.0,
    reviews: 42,
    description: 'Sebuah tempat peristirahatan yang elegan, suite seluas 120 m² ini menawarkan pemandangan Gunung Lawu yang memukau, kolam renang pribadi, dan teras yang sempurna untuk menikmati momen golden hour. Di dalamnya, temukan furnitur tradisional Jawa yang diukir tangan, fasilitas premium, dan kamar mandi bergaya spa untuk memanjakan diri Anda.',
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=800&auto=format&fit=crop',
    ],
    category: 'family',
    facilities: [
      { name: 'Wi-Fi Kecepatan Tinggi', icon: 'Wifi' },
      { name: 'Parkir Gratis', icon: 'Car' },
      { name: 'Kamar Mandi Spa', icon: 'Bath' },
      { name: 'Minuman Premium', icon: 'Wine' },
      { name: 'Meja Kerja & Charging', icon: 'Briefcase' },
      { name: 'Housekeeping Harian', icon: 'Sparkles' },
      { name: 'Layanan Kamar 24 Jam', icon: 'Clock' },
      { name: 'Layanan Unpacking', icon: 'Shirt' },
      { name: 'Akses Area Wellness', icon: 'Heart' },
    ],
    bookingPolicy: 'Check-in dari 14:00 - 23:59',
    isPopular: true,
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
  },
  {
    id: '4',
    name: 'Triangle Eco-Pod',
    location: 'Gondosuli, Tawangmangu',
    coordinates: { lat: -7.6670, lng: 111.1340 },
    price: 900000,
    rating: 4.7,
    reviews: 56,
    description: 'A unique A-frame experience. Compact, cozy, and extremely photogenic. Wake up to the sound of birds and the smell of pine trees right outside your door.',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1499722616228-7a1a5f2a41f5?q=80&w=800&auto=format&fit=crop',
    ],
    category: 'couple',
    facilities: [
      { name: 'Heater', icon: 'Thermometer' },
      { name: 'Breakfast', icon: 'Coffee' },
    ],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
  },
];